### ISSUE TITLE
explain bitmask

### ISSUE THREAD

**Issue by samuelweiler** [hstenn/ietf-ntp-extended-information-ef#4]
the document does not make clear that the content descriptor is a bitmask - other than by implication.  be explicit.  Also see issue #1 - you may just want to define two bits - or even some simpler way of telling which of these data elements is present in this EF.  (Does it make sense to break this into two separate extensions?)

**Comment by samweiler** [comment]
The example at the end of section 2 is what makes it clear that you're using a bitmask, and only when you look at the ASCII art.  I recall a former IETF area director being quite firm that documents needed to make sense without the pictures for accessibility reasons.  This one doesn't.

That said, if you remove the extensibility, as I suggest in issue #1 and as Danny suggested in issue #8  , this could become moot.

**Comment by hstenn** [comment]
resolved by    e48af8a..81cd42d  master -> master
