### ISSUE TITLE
add pointer back to this repo

### ISSUE THREAD

**Issue by samuelweiler** [hstenn/ietf-ntp-extended-information-ef#6]
Add a link back to this repository, suggesting that feedback be sent here.

**Comment by hstenn** [comment]
Got a recommendation on the language for that?

**Comment by samweiler** [comment]
Here are two I have seen recently:

 >   The source for this draft is maintained in GitHub at:
   https://github.com/hstenn/ietf-ntp-extended-information-ef


>   RFC EDITOR: PLEASE REMOVE THE FOLLOWING PARAGRAPH BEFORE PUBLISHING:
> The source code and issues list for this draft can be found in
   https://github.com/hstenn/ietf-ntp-extended-information-ef
