### ISSUE TITLE
abstract/intro the same

### ISSUE THREAD

**Issue by samweiler** [hstenn/ietf-ntp-extended-information-ef#7]
Relaying Danny's comment from in the 7 March 2019 call: abstract/intro shouldn't be the same.

**Comment by samweiler** [comment]
To answer Harlan's question re: documents that do otherwise, here is a good example: https://tools.ietf.org/html/draft-brotman-rdbd-01

(These authors also made significant revisions to their proposal just a week and a half after issuing it!)

**Comment by hstenn** [comment]
Resolved in one of the commits I just made.
